### ISSUE TITLE
Custom back-end support

### ISSUE THREAD

**Issue by at88mph** [cloud-elements/cloud-file-browser-nodejs#3]
Hi there,

I'm extremely interested in the cloud file browser, and I'd like to incorporate it into our science cloud of astronomical data.

We don't currently use OAuth, though we would like to in the future, and we have our own cloud of servers.  Is it possible to support custom back ends that want to use X509 certificates or username and password?

I would be really happy to contribute back to the project as needed, too, as we have features like folder quotas and setting Group permissions on files and folders that are required.

Many thanks,
Dustin

**Comment by at88mph** [comment]
Hi there,

I'm more curious as to whether this project is still in development, and how to add a custom backend that isn't in the currently registered elements 'main' list.

Many thanks,
Dustin

**Comment by markwilliams970** [comment]
Dustin, thanks for your interest in filebrowser.io! Your astronomical data cloud sounds very interesting. Apologies for the slow follow-up. The project isn't currently being actively worked, but Cloud Elements plans to maintain the toolkit. Our team would certainly be interested to review any additions/pull requests.

In terms of adding a custom backend, it would primarily involve adding new callbacks to [server.js](https://github.com/cloud-elements/cloud-file-browser-nodejs/blob/master/server.js) that would then make http requests into whatever custom API you have in mind. It would probably make sense to add handlers/clauses in app.all for some added url endpoints that would associate to your custom functionality. Of course, it would be helpful to add node.js abstractions/methods around the custom backend you have in mind too. Insofar as backend authentication is concerned, basic auth username/password is certainly feasible with node http. I'm not sure about X509 though.

Thanks again for your interest/feedback! Mark Williams, Cloud Elements Support

**Comment by at88mph** [comment]
@markwilliams970 Thank you very much for the reply.

The server.js filters the supported Clouds, but what supplies the entire list of available Clouds?  Meaning, the resource that handles the /elements call.

Thanks again, Mark.

**Comment by cephil** [comment]
@at88mph Dustin,

Sorry for the delay in response -- it's been a little bit since I've worked in this code, so I took some time to review it before getting back with you.

As you noticed, the list of clouds provided to the UI is controlled in server.js -- essentially hardcoding them and defining their parameters. The elements and their tokens are managed by our main web app, console.cloud-elements.com. The API `https://console.cloud-elements.com/elements` connects the application to the various clouds. 

As for creating new abstractions, you could create handlers for any custom clouds you wanted to support, potentially by catching your own custom URL in the node.js server (e.g. server.js line 177) and handling their respective APIs inside this method you create. 

Also, take a look at http://cloud-elements.com/hubs/documents-hub/ , as we have added support for more clouds. If any of these are clouds that you need to support, you could follow the same pattern defined in server.js and add the elementTokens for these specific clouds. The only other thing you should have to do would be to add the corresponding logos into the CSS based on the class name that gets generated. 

Thanks, and let me know if there's anything else I can do to help!

Phil
